export const componentKeys = {
    "employment": "EMP",
    "education": "EDU",
    "permanentaddress": "ADR",
    "courtrecord": "COU",
    "criminalrecord": "CRI",
    "identity": "IDE",
    "currentaddress": "ADR",
    // "socialmedia": "SOC",
    // "globaldatabase": "GLB",
    // "reference": "REF",
    // "drugtestfive": "DRTFV",
    // "drugtestten": "DRTTN",
    // "passport": "PAS",
    // "addresstelephone": "ADRTEL",
    // "addresscomprehensive": "ADRCMP",
    // "educationcomprehensive": "EDUCMP",
    // "educationadvanced": "EDUADV",
    // "drugtestsix": "DRTSX",
    // "drugtestseven": "DRTSV",
    // "drugtesteight": "DRTET",
    // "drugtestnine": "DRTNE",
    // "facisl3": "FAl",
    // "credittrans": "CRDTR",
    // "creditequifax": "CRDEQ",
    // "empadvance": "EMPAD",
    // "empbasic": "EMPBS",
    // "vddadvance": "VDAD",
    // "dlcheck": "DL",
    // "voterid": "VOT",
    // "ofac": "OFAC",
    // "gapvfn": "GAPFN",
    // "bankstmt": "BNKST",
    // "refbasic": "REFBS",
    // "directorshipcheck": "DIRSH",
    // "addressonline": "ADRON",
    // "physostan": "PHY",
    // "sitecheck": "STC",
    // "uan": "UAN",
    // "addressbusiness": "ADRBUS",
    // "caconfirmation": "CACNF",
    // "colorblindness": "CLRBL",
    // "exitinterview": "EXTINT",
    // "epfo": "EPFO",
    // "twentysixas": "TWTSX",
    // "vddpv": "VDPV",
    // "vdddeclaration": "VDDCL",
    // "tcsvdd": "TCVD",
    // "uanhidden": "UANHD",
    // "bankstmthidden": "BNSHD",
    // "cvanalysis": "CVAN",
    // "sanctioncheck": "SAN",
    // "refdigital": "REFD",
    // "formsixteen": "FRMSX",
    // "aadhaarfinger": "ADHFN",
    // "aadhaarverification": "ADHVF",
    // "addresspostal": "ADRPR",
    // "videokyc": "VDKY",
    // "vddcomprehensive": "VDCMP",
    // "vddbasic": "VDBS",
    // "physicalsitecheck": "PHYSC",
    // "psychometriccustomized": "PSYCS",
    // "pcc": "PCC",
    // "pan": "PAN",
    // "drugtesthair": "DRTHR",
    // "drugtesttwelve": "DRTTW",
    // "drugtesttena": "DRTTNA",
    // "cpclawfirm": "CPCFR",
    // "crconline": "CRCON",
    // "crcphysical": "CRCPY",
    // "certificateverification": "CRVF",
    // "refcomprehensive": "REFCMP",
    // "hl": "HL",
    // "gs": "GS",
    // "discert": "DSC",
    // "offerdeclined": "OFDC",
    // "sam": "SAM",
    // "refvdd": "REFVF",
    // "epfohidden": "EPHD",
    // "drugtestelevan": "DRTEL",
    // "globalmediasearch": "GLBSE",
    // "empintl": "EMPIN",
    // "eduintl": "EDUIN",
    // "ssntrace": "SSTR",
    // "criminalfederal": "CRFD",
    // "criminalcounty": "CRMCT",
    // "civilliti": "CVLT",
    // "techmpassport": "TCHP",
    // "techmgdb": "TCHGB",
    // "techmgapcheck": "TCHGP",
    // "techmcreditcheck": "TCHCC",
    // "techmdrugfive": "TCHDF",
    // "techmdrugten": "TCHDT",
    // "techmaddress": "TCHADR",
    // "techmeducation": "TCHED",
    // "techmemployment": "TCHEMP",
    // "uananalysis": "UANAN"
};
