const mongoose = require('mongoose');
const CaseSchema = mongoose.Schema({
	caseId:{type:String,required:true,unique:true},
    candidateName:{type:String,required:true},
    employeeId:{type:String},	
    batch:{type:mongoose.Schema.Types.ObjectId,ref:'Batch'},
    client:{type:mongoose.Schema.Types.ObjectId,ref:'Client',required:true},
    subclient:{type:mongoose.Schema.Types.ObjectId,ref:"Subclient",required:true},
    package:{type:mongoose.Schema.Types.ObjectId,ref:'ClientContractPackage',required:false},
    profile:{type:mongoose.Schema.Types.ObjectId,ref:'ClientContractProfile',required:false},
    casePriority:{type:String},
    uploadDate:{type:Date},
    initiationDate:{type:Date},
    tatEndDate:{type:Date},
    dataEntryCompletionDate:{type:Date},
    inputqcCompletionDate:{type:Date},
    outputqcCompletionDate:{type:Date},
    reportDate:{type:Date},
    comments:[],
    caseStopDate:{type:Date},
    reinitiationDate:{type:Date},
    firstInsufficiencyRaisedDate:{type:Date},
    lastInsufficiencyClearedDate:{type:Date},
    status:{type:String},
    cde:{type:Boolean},
    candidateEmail:{type:String},	
    grade:{type:String},
    grade1:{type:mongoose.Schema.Types.ObjectId,ref:'ColorMaster',default:null},	
    gradingComments:{type:String},
    reportType:{type:String},
    inputqcCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User',default:null},	
    outputqcCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User',default:null},	
    componentsToCheck:[],
// Added by Arjun on 22nd November 2022    
    outputqcAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User',default:null},
    outputqcAllocationDate:{type:Date},
// End Add by Arjun on 22nd November 2022    
    dataEntryAllocationDate:{type:Date},
    dataEntryAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User',default:null},
    additionalChecks:[],
    actualChecksInCase:[],
    personalDetails:{type:mongoose.Schema.Types.ObjectId,ref:"PersonalDetailsData"},
    invoiceAmount:{type:Number},
    invoiceDate:{type:Date},
    invoiceNumber:{type:String},
    numberOfChecksEntered:{type:Number},
    numberOfAdditionalChecks:{type:Number},
    colorType:{type:String},	
    actualComponents:[],
    archived: { type: Boolean },
    archivedOn: { type: Date },	
    unArchivedOn: { type: Date },
    unArchivedBy: {type:mongoose.Schema.Types.ObjectId,ref:'User'},
    modifiedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
    modifiedOn:{type:Date,default:Date.now},
    interimReportDate:{type:Date},
    interimReportUploadedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User',default:null}
})

module.exports = mongoose.model('Case',CaseSchema);
