
    const mongoose = require('mongoose')
const nationalitywithrighttoworkSchema = mongoose.Schema({
mov:{type:String},movRhs:{type:String},
case:{type:mongoose.Schema.Types.ObjectId,ref:'Case',required:true},
comments:[],
colorType:{type:String},
checkId: {type:String},
serialNumber:{type:Number},
// efforts:{type:Number},
client:{type:mongoose.Schema.Types.ObjectId,ref:'Client'},
subclient:{type:mongoose.Schema.Types.ObjectId,ref:'Subclient'},	
component:{type:mongoose.Schema.Types.ObjectId,ref:'Component'},
personalDetailsData:{type:mongoose.Schema.Types.ObjectId,ref:'PersonalDetailsData'},

name:{type:String},
nameRhs:{type:String},
fathername:{type:String},
fathernameRhs:{type:String},
dob:{type:String},
dobRhs:{type:String},
idtype:{type:String},
idtypeRhs:{type:String},
idnumber:{type:String},
idnumberRhs:{type:String},
verifiedbyRhs:{type:String},
verifiedonRhs:{type:Date},
remarksRhs:{type:String},
 
earlierStage:{type:String},
stage:{type:String},
status:{type:String},
onHoldComments:{type:String},
onHoldCommentsDate:{type:Date},
updateLhsComments:{type:String},
updateLhsDate:{type:Date},	
nextfollowupdate:{type:String},
expectedclosuredate:{type:String},
insufficiencyRaisedDate:{type:Date},
insufficiencyClearedDate:{type:Date},
insufficiencyClearanceRejectionDate:{type:Date},
insufficiencyComments:{type:String},
insufficiencyClearedComments:{type:String},
insufficiencyRejectionComments:{type:String},
insufficiencyClearanceRejectionComments:{type:String},
insufficiencyClearanceRejectedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
dataEntryCompletionDate:{type:Date},
dataEntryCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
inputqcComments:{type:String},
inputqcCompletionDate:{type:Date},
branchAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'Branch'},
verificationAllocatedDate:{type:Date},
verificationAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
mentorAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
allocatedToFE:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
feAllocationDate:{type:Date},
allocatedToVendor:{type:mongoose.Schema.Types.ObjectId,ref:'Vendor'},
vendorAllocationDate:{type:Date},
feInsufficiencyComments:{type:String},
feVerificationCompletionDate:{type:String},
vendorInsufficiencyComments:{type:String},
vendorVerificationCompletionDate:{type:String},
verifierReviewComments:{type:String},
verificationStatus:{type:String},
verificationComments:{type:String},
verificationCompletionDate:{type:Date},
verificationCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
personContacted:{type:String},
contactNumberOfPersonContacted:{type:String},
mentorReviewComments:{type:String},
mentorReviewCompletionDate:{type:Date},
mentorReviewCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
scrutinyRejectionReason:{type:String},
scrutinyApprovedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
clientClearanceRemarks:{type:String},
clientClearedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
outputqcComments:{type:String},
outputqcCompletionDate:{type:Date},
reinitiationComments:{type:String},
reinitiationDate:{type:Date},
grade:{type:String},
gradingComments:{type:String},
effortType:{type:String},
interimOrFinal:{type:String},
nextfollowupdate:{type:String},
expectedclosuredate:{type:String},
mode:{type:String},
modifiedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
modifiedOn:{type:Date,default:Date.now}
})
module.exports = mongoose.model('nationalitywithrighttowork',nationalitywithrighttoworkSchema);

    