const 5paneldrugabusetest = require('../controllers/data_entry/5paneldrugabusetest.controller');
const express = require('express');
const router = express.Router();

router.post("/",5paneldrugabusetest.create);
router.get("/:case",5paneldrugabusetest.findAllForACase);
router.get("/findone/:caseId/:componentId",5paneldrugabusetest.findOne);
router.post("/uploadfile",5paneldrugabusetest.uploadFile);
router.post("/uploadproofofwork",5paneldrugabusetest.uploadProofOfWork);
router.post("/uploadpvproofofwork",5paneldrugabusetest.uploadPvProofOfWork);
router.post("/uploadpaymentproof",5paneldrugabusetest.uploadPaymentProof);
router.delete("/deletefile/:caseId/:componentName/:componentId/:fileName",5paneldrugabusetest.deleteFile);
router.get("/downloadfile/:caseId/:componentName/:componentId",5paneldrugabusetest.downloadFile);
router.get("/downloadproofofwork/:caseId/:componentName/:componentId",5paneldrugabusetest.downloadProofOfWork);
router.get("/downloadpaymentproof/:caseId/:componentName/:componentId",5paneldrugabusetest.downloadPaymentProof);
router.get("/readfilenames/:caseId/:componentName/:componentId",5paneldrugabusetest.readFileNames);
router.get("/readproofofworks/:caseId/:componentName/:componentId",5paneldrugabusetest.readProofOfWorks);
router.get("/readpaymentproofs/:caseId/:componentName/:componentId",5paneldrugabusetest.readPaymentProofs);
router.put("/:caseId/:componentId",5paneldrugabusetest.update);
router.put("/updatedataentrystatus/:caseId/:componentId",5paneldrugabusetest.updateDataEntryStatus);
router.put("/updateinputqcstatus/:caseId/:componentId",5paneldrugabusetest.updateInputqcStatus);
router.put("/updateverificationstatus/:caseId/:componentId",5paneldrugabusetest.updateVerificationStatus);
router.put("/updatefeverificationstatus/:caseId/:componentId",5paneldrugabusetest.updateFeVerificationStatus);
router.put("/updatevendorverificationstatus/:caseId/:componentId",5paneldrugabusetest.updateVendorVerificationStatus);
router.put("/updateverifierreviewstatus/:caseId/:componentId",5paneldrugabusetest.updateVerifierReviewStatus);
router.put("/updatementorreviewstatus/:caseId/:componentId",5paneldrugabusetest.updateMentorReviewStatus);
router.put("/updateoutputqcstatus/:caseId/:componentId",5paneldrugabusetest.updateOutputqcStatus);
router.put("/approveinsuff2/:caseId/:componentId",5paneldrugabusetest.approveInsuff2);
router.put("/rejectinsuff2/:caseId/:componentId",5paneldrugabusetest.rejectInsuff2);
router.put("/clearinsuff1/:caseId/:componentId",5paneldrugabusetest.clearInsuff1);
router.put("/clearinsuff2/:caseId/:componentId",5paneldrugabusetest.clearInsuff2);
router.put("/rejectinsuff1clearance/:caseId/:componentId",5paneldrugabusetest.rejectInsuff1Clearance);
router.put("/rejectinsuff2clearance/:caseId/:componentId",5paneldrugabusetest.rejectInsuff2Clearance);
router.put("/allocatechecktomyself/:caseId/:componentId",5paneldrugabusetest.allocateCheckToMyself);
router.get("/user/getallchecksallocatedtomeforverification",5paneldrugabusetest.getAllChecksAllocatedToMeForVerification);
router.get("/insuff/insuffforclient",5paneldrugabusetest.getInsuffForClient);
router.get("/insuff/insuffforscrutiny",5paneldrugabusetest.getInsuffForScrutiny);
router.put("/approveinsuffclearance/:caseId/:componentId",5paneldrugabusetest.approveInsuffClearance);
router.delete("/deletecheck/case/:caseId/component/:componentId",5paneldrugabusetest.deleteCheck);
router.put("/putittofebucket/:caseId/:componentId",5paneldrugabusetest.putItToFeBucket);
router.put("/putittovendorbucket/:caseId/:componentId",5paneldrugabusetest.putItToVendorBucket);
router.put("/allocatechecktofe/:caseId/:componentId",5paneldrugabusetest.allocateCheckToFe);
router.put("/allocatechecktovendor/:caseId/:componentId",5paneldrugabusetest.allocateCheckToVendor);
router.put("/allocatechecktoverifier/:caseId/:componentId",5paneldrugabusetest.allocateCheckToVerifier);
router.put("/addnote/:caseId/:componentId",5paneldrugabusetest.addNote);
router.get("/findcomponentsfor/:for",5paneldrugabusetest.findComponentsFor)
router.get("/findcomponentsforvendormanager/:status",5paneldrugabusetest.findComponentsForVendorManager)
router.get("/find/unallocated/verification/",5paneldrugabusetest.findUnallocatedComponentsForVerification)
router.put("/reinitiatecheck/:caseId/:componentId",5paneldrugabusetest.reinitiateCheck);
module.exports = router;
