const tickticktick = require('../controllers/data_entry/tickticktick.controller');
const express = require('express');
const router = express.Router();

router.post("/",tickticktick.create);
router.get("/:case",tickticktick.findAllForACase);
router.get("/findone/:caseId/:componentId",tickticktick.findOne);
router.post("/uploadfile",tickticktick.uploadFile);
router.post("/uploadproofofwork",tickticktick.uploadProofOfWork);
router.post("/uploadpvproofofwork",tickticktick.uploadPvProofOfWork);
router.post("/uploadpaymentproof",tickticktick.uploadPaymentProof);
router.delete("/deletefile/:caseId/:componentName/:componentId/:fileName",tickticktick.deleteFile);
router.get("/downloadfile/:caseId/:componentName/:componentId/:fileName",tickticktick.downloadFile);
router.get("/downloadproofofwork/:caseId/:componentName/:componentId/:fileName",tickticktick.downloadProofOfWork);
router.get("/downloadpaymentproof/:caseId/:componentName/:componentId/:fileName",tickticktick.downloadPaymentProof);
router.get("/readfilenames/:caseId/:componentName/:componentId",tickticktick.readFileNames);
router.get("/readproofofworks/:caseId/:componentName/:componentId",tickticktick.readProofOfWorks);
router.get("/readpaymentproofs/:caseId/:componentName/:componentId",tickticktick.readPaymentProofs);
router.put("/:caseId/:componentId",tickticktick.update);
router.put("/updatedataentrystatus/:caseId/:componentId",tickticktick.updateDataEntryStatus);
router.put("/updateinputqcstatus/:caseId/:componentId",tickticktick.updateInputqcStatus);
router.put("/updateverificationstatus/:caseId/:componentId",tickticktick.updateVerificationStatus);
router.put("/updatefeverificationstatus/:caseId/:componentId",tickticktick.updateFeVerificationStatus);
router.put("/updateverifierreviewstatus/:caseId/:componentId",tickticktick.updateVerifierReviewStatus);
router.put("/updatementorreviewstatus/:caseId/:componentId",tickticktick.updateMentorReviewStatus);
router.put("/updateoutputqcstatus/:caseId/:componentId",tickticktick.updateOutputqcStatus);
router.put("/approveinsuff2/:caseId/:componentId",tickticktick.approveInsuff2);
router.put("/rejectinsuff2/:caseId/:componentId",tickticktick.rejectInsuff2);
router.put("/clearinsuff1/:caseId/:componentId",tickticktick.clearInsuff1);
router.put("/clearinsuff2/:caseId/:componentId",tickticktick.clearInsuff2);
router.put("/rejectinsuff1clearance/:caseId/:componentId",tickticktick.rejectInsuff1Clearance);
router.put("/rejectinsuff2clearance/:caseId/:componentId",tickticktick.rejectInsuff2Clearance);
router.put("/allocatechecktomyself/:caseId/:componentId",tickticktick.allocateCheckToMyself);
router.get("/user/getallchecksallocatedtomeforverification",tickticktick.getAllChecksAllocatedToMeForVerification);
router.get("/insuff/insuffforclient",tickticktick.getInsuffForClient);
router.get("/insuff/insuffforscrutiny",tickticktick.getInsuffForScrutiny);
router.put("/approveinsuffclearance/:caseId/:componentId",tickticktick.approveInsuffClearance);
router.get("/findcomponentsfor/:for",tickticktick.findComponentsFor)
module.exports = router;
