
    const mongoose = require('mongoose')
const employmenttest3Schema = mongoose.Schema({
case:{type:mongoose.Schema.Types.ObjectId,ref:'Case',required:true},
comments:[],
colorType:{type:String},
checkId: {type:String},
serialNumber:{type:Number},
// efforts:{type:Number},
client:{type:mongoose.Schema.Types.ObjectId,ref:'Client'},
subclient:{type:mongoose.Schema.Types.ObjectId,ref:'Subclient'},	
component:{type:mongoose.Schema.Types.ObjectId,ref:'Component'},
personalDetailsData:{type:mongoose.Schema.Types.ObjectId,ref:'PersonalDetailsData'},

organization:{type:String},
organizationRhs:{type:String},
location:{type:String},
locationRhs:{type:String},
contactno:{type:String},
contactnoRhs:{type:String},
empid:{type:String},
empidRhs:{type:String},
doj:{type:String},
dojRhs:{type:String},
dor:{type:String},
dorRhs:{type:String},
designation:{type:String},
designationRhs:{type:String},
remuneration:{type:String},
remunerationRhs:{type:String},
reasonforleaving:{type:String},
reasonforleavingRhs:{type:String},
activeRhs:{type:String},
verifiernameRhs:{type:String},
verifierdesignationRhs:{type:String},
verifieremailidRhs:{type:String},
dutiesandresponsibilitiesRhs:{type:String},
integrityRhs:{type:String},
officialresgRhs:{type:String},
eligibleRhs:{type:String},
exitformalitiesRhs:{type:String},
verifiedbyRhs:{type:String},
verifiedonRhs:{type:Date},
 
earlierStage:{type:String},
stage:{type:String},
status:{type:String},
onHoldComments:{type:String},
onHoldCommentsDate:{type:Date},
updateLhsComments:{type:String},
updateLhsDate:{type:Date},	
nextfollowupdate:{type:String},
expectedclosuredate:{type:String},
insufficiencyRaisedDate:{type:Date},
insufficiencyClearedDate:{type:Date},
insufficiencyClearanceRejectionDate:{type:Date},
insufficiencyComments:{type:String},
insufficiencyClearedComments:{type:String},
insufficiencyRejectionComments:{type:String},
insufficiencyClearanceRejectionComments:{type:String},
insufficiencyClearanceRejectedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
dataEntryCompletionDate:{type:Date},
dataEntryCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
inputqcComments:{type:String},
inputqcCompletionDate:{type:Date},
branchAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'Branch'},
verificationAllocatedDate:{type:Date},
verificationAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
mentorAllocatedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
allocatedToFE:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
feAllocationDate:{type:Date},
allocatedToVendor:{type:mongoose.Schema.Types.ObjectId,ref:'Vendor'},
vendorAllocationDate:{type:Date},
feInsufficiencyComments:{type:String},
feVerificationCompletionDate:{type:String},
vendorInsufficiencyComments:{type:String},
vendorVerificationCompletionDate:{type:String},
verifierReviewComments:{type:String},
verificationStatus:{type:String},
verificationComments:{type:String},
verificationCompletionDate:{type:Date},
verificationCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
personContacted:{type:String},
contactNumberOfPersonContacted:{type:String},
mentorReviewComments:{type:String},
mentorReviewCompletionDate:{type:Date},
mentorReviewCompletedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
scrutinyRejectionReason:{type:String},
scrutinyApprovedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
clientClearanceRemarks:{type:String},
clientClearedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
outputqcComments:{type:String},
outputqcCompletionDate:{type:Date},
reinitiationComments:{type:String},
reinitiationDate:{type:Date},
grade:{type:String},
gradingComments:{type:String},
effortType:{type:String},
interimOrFinal:{type:String},
nextfollowupdate:{type:String},
expectedclosuredate:{type:String},
mode:{type:String},
modifiedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},
modifiedOn:{type:Date,default:Date.now}
})
module.exports = mongoose.model('employmenttest3',employmenttest3Schema);

    